### ISSUE TITLE
Provide ready-to-use Docker images

### ISSUE THREAD

**Issue by CDDelta** [ArweaveTeam/testweave-docker#3]
It would be very helpful to have the container image ready to use just by running `docker pull`. The image can be stored along with this repo using the GitHub Container Registry which is free for OSS.

A GitHub action can be set up to build the image every time a GitHub release is created.

Something like the below will be sufficient. I can't set this up as someone from the team will need to provide a credential for pushing the image to the repo.

For setting up `CR_PAT`: https://docs.github.com/en/packages/guides/migrating-to-github-container-registry-for-docker-images#authenticating-with-the-container-registry
```yaml
name: Build Release

on:
  release:
    types: [created]

jobs:
  build_image:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}   <- The repo owner needs to generate a credential for pushing to the registry
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/gateway.dockerfile
          push: true
          tags: |
            ghcr.io/ArweaveTeam/testweave:latest
            ghcr.io/ArweaveTeam/testweave:${{ github.event.release.tag_name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
```
